import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cross Carbon</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Hero />

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ 🇨🇴 🇨🇿
        </a>
      </footer>
    </div>
  );
};

export default Home;
